name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Svelte project
        run: npm run build

      - name: Deploy to build branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout --orphan build
          git --work-tree=dist add --all
          git --work-tree=dist commit -m 'Build output'
          git push origin HEAD:build --force
